---
- name: Install disk
  when: disk_uninstall == false
  block:
    - name: Install
      ansible.builtin.include_tasks: install.yml  

    - name: Setup
      ansible.builtin.include_tasks: setup.yml

- name: Uninstall disk
  when: disk_uninstall == true
  block:
    - name: Clean
      ansible.builtin.include_tasks: clean.yml
